name: manual-workflow

on: workflow_dispatch # manual trigger
 # on : 
 #  push : 
 #    branches: main -> automatic trigger on push to main branch

 # on:
 #  schedule:
 #  - cron: '0 0 * * *' -> automatic trigger on schedule (every day at midnight)

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
